[project]
name = "5-api-handling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=1.97.1",
    "openai-agents>=0.2.3",
]
